### ISSUE TITLE
Not sure what's happening, script catching NullPointerExceptions at multiple methods

### ISSUE THREAD

**Issue by shoeJuice** [justalemon/PlayerCompanion#1]
Hiya! I was able to boot up the mod and it looks awesome! Weirdly enough I see another name below mine when it boots up, and the instant I open my inventory the script crashes. I checked the log and I consistently find this error. I've no other mods but a NoReticule mod in my scripts folder with SHDVN up to date.

[11:46:55] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[11:46:55] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[11:46:55] [DEBUG] Loading scripts from D:\Rockstar Games North\Grand Theft Auto V\scripts ...
[11:46:55] [DEBUG] Loading assembly GGOV.dll ...
[11:46:55] [INFO] Found 1 script(s) in GGOV.dll resolved to API 3.1.0.
[11:46:55] [DEBUG] Loading assembly LemonUI.FiveM.net.dll ...
[11:46:55] [ERROR] Failed to load assembly LemonUI.FiveM.net.dll: System.IO.FileNotFoundException: Could not load file or assembly 'CitizenFX.Core.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'CitizenFX.Core.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[11:46:55] [DEBUG] Loading assembly LemonUI.SHVDN2.dll ...
[11:46:56] [INFO] Found 0 script(s) in LemonUI.SHVDN2.dll.
[11:46:56] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[11:46:56] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[11:46:56] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[11:46:56] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[11:46:56] [DEBUG] Loading assembly NoReticle.dll ...
[11:46:56] [INFO] Found 1 script(s) in NoReticle.dll resolved to API 2.10.14.
[11:46:56] [DEBUG] Loading assembly PlayerCompanion.dll ...
[11:46:56] [INFO] Found 1 script(s) in PlayerCompanion.dll resolved to API 3.1.0.
[11:46:56] [DEBUG] Instantiating script GGO.GGO ...
[11:46:58] [INFO] Started script GGO.GGO.
[11:46:58] [DEBUG] Instantiating script NoReticle.Class1 ...
[11:46:58] [INFO] Started script NoReticle.Class1.
[11:46:58] [DEBUG] Instantiating script PlayerCompanion.Companion ...
[11:46:58] [INFO] Started script PlayerCompanion.Companion.
[11:46:58] [ERROR] Caught fatal unhandled exception:
System.IO.FileNotFoundException: Could not load file or assembly 'CitizenFX.Core.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'CitizenFX.Core.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at PlayerCompanion.InventoryManager.PopulateItems()
   at PlayerCompanion.Companion.Companion_Tick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[11:46:59] [ERROR] The exception was thrown while executing the script PlayerCompanion.Companion.
[11:46:59] [WARNING] Aborted script PlayerCompanion.Companion.
[11:47:18] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GGO.Inventory.PlayerInventory.UpdateItems()
   at GGO.Inventory.PlayerInventory.Process()
   at LemonUI.ObjectPool.Process()
   at GGO.GGO.HUD_Tick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[11:47:18] [ERROR] The exception was thrown while executing the script GGO.GGO.
[11:47:18] [WARNING] Aborted script GGO.GGO.

**Comment by justalemon** [comment]
You installed the FiveM version of LemonUI on SHVDN.
